import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar/NavBar'
import { StoreProvider } from './StoreProvider'
import Footer from '@/components/Footer/Footer'
import { NavBarProvider } from '@/context/NavBarContext'

/* const geistSans = Geist({
	variable: '--font-',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
}) */

export const metadata: Metadata = {
	title: {
		template: '%s - Додо Пицца',
		default: 'Додо Пицца',
	},
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={`font-nimbus  antialiased`}>
				<main className='w-full min-h-screen flex flex-col items-center'>
					<div className='md:w-[90%] lg:w-[80%] xl:w-[73%]'>
						<StoreProvider>
							<NavBarProvider>{children}</NavBarProvider>
						</StoreProvider>
					</div>
					<Footer />
				</main>
			</body>
		</html>
	)
}
