import type { Metadata } from 'next'
import './globals.css'
import { StoreProvider } from './StoreProvider'
import Footer from '@/components/Footer/Footer'
import { NavBarProvider } from '@/context/NavBarContext'
import Messager from '@/components/Messager'

export const metadata: Metadata = {
	title: {
		template: '%s - Додо Пицца',
		default: 'Додо Пицца',
	},
	description: 'Generated by create next app',
	icons: {
		icon: ['/icon.ico'],
	},
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={`font-nimbus  antialiased`}>
				<main className='w-full min-h-screen flex flex-col items-center'>
					<StoreProvider>
						<NavBarProvider>
							{children}
							<Messager />
						</NavBarProvider>
					</StoreProvider>
					<Footer />
				</main>
			</body>
		</html>
	)
}
