export const PAGES = {
	PIZZA: '/pizza',
	COMBO: '/combo',
	SNACKS: '/snacks',
	COCKTAILS: '/cocktails',
	COFFEE: '/coffee',
	DRINKS: '/drinks',
	DESSERTS: '/desserts',
	SAUSE: '/sause',
	OTHERSTUFF: '/otherStuff',
	NEW: '/new',
	BREAKFAST: '/breakfast',
	OTHER: '/other',
	STOCKS: '/stocks',
} as const

export const API_ENDPOINTS = {
	Пицца: 'pizza',
	Комбо: 'combo',
	Закуски: 'snacks',
	Коктейли: 'cocktails',
	Кофе: 'coffee',
	Напитки: 'drinks',
	Десерты: 'desserts',
	Соусы: 'sause',
	'Другие товары': 'otherstuff',
	Новинки: 'new',
	Завтрак: 'breakfast',
	Хиты: 'hit',
	'На компанию': 'company',
	'Любят дети': 'children',
} as const
